### ISSUE TITLE
The requested package php-soap could not be found 

### ISSUE THREAD

**Issue by HRIT-Florian** [bmoex/Lumesse-TalentLink#2]
Installation via composer fails 

Composer Log:

> 
The requested package php-soap could not be found in any version, there may be a typo in the package name.

**Comment by bmoex** [comment]
Good find. Should probably be ext-soap. Will check.

**Comment by bmoex** [comment]
Can you try again? I changed it directly through github :-)

**Comment by HRIT-Florian** [comment]
That's it https://github.com/bmoex/Lumesse-TalentLink/commit/46a96d33dfb9cf3c535a03383a94d315e60d1d2e 👍  Many Thanks!

**Comment by bmoex** [comment]
I submitted this repository to packagist too, so you can use composer as intended too ;-)
